// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battlelog.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BattleLogUser struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	PilotName            string   `protobuf:"bytes,3,opt,name=pilot_name,json=pilotName,proto3" json:"pilot_name,omitempty"`
	GameParam            []byte   `protobuf:"bytes,4,opt,name=game_param,json=gameParam,proto3" json:"game_param,omitempty"`
	BattleCount          int32    `protobuf:"varint,5,opt,name=battle_count,json=battleCount,proto3" json:"battle_count,omitempty"`
	WinCount             int32    `protobuf:"varint,6,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`
	LoseCount            int32    `protobuf:"varint,7,opt,name=lose_count,json=loseCount,proto3" json:"lose_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleLogUser) Reset()         { *m = BattleLogUser{} }
func (m *BattleLogUser) String() string { return proto.CompactTextString(m) }
func (*BattleLogUser) ProtoMessage()    {}
func (*BattleLogUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bd4546689e62ffe, []int{0}
}

func (m *BattleLogUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleLogUser.Unmarshal(m, b)
}
func (m *BattleLogUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleLogUser.Marshal(b, m, deterministic)
}
func (m *BattleLogUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleLogUser.Merge(m, src)
}
func (m *BattleLogUser) XXX_Size() int {
	return xxx_messageInfo_BattleLogUser.Size(m)
}
func (m *BattleLogUser) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleLogUser.DiscardUnknown(m)
}

var xxx_messageInfo_BattleLogUser proto.InternalMessageInfo

func (m *BattleLogUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BattleLogUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *BattleLogUser) GetPilotName() string {
	if m != nil {
		return m.PilotName
	}
	return ""
}

func (m *BattleLogUser) GetGameParam() []byte {
	if m != nil {
		return m.GameParam
	}
	return nil
}

func (m *BattleLogUser) GetBattleCount() int32 {
	if m != nil {
		return m.BattleCount
	}
	return 0
}

func (m *BattleLogUser) GetWinCount() int32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

func (m *BattleLogUser) GetLoseCount() int32 {
	if m != nil {
		return m.LoseCount
	}
	return 0
}

type BattleLogMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Seq                  uint32   `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp            int64    `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleLogMessage) Reset()         { *m = BattleLogMessage{} }
func (m *BattleLogMessage) String() string { return proto.CompactTextString(m) }
func (*BattleLogMessage) ProtoMessage()    {}
func (*BattleLogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bd4546689e62ffe, []int{1}
}

func (m *BattleLogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleLogMessage.Unmarshal(m, b)
}
func (m *BattleLogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleLogMessage.Marshal(b, m, deterministic)
}
func (m *BattleLogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleLogMessage.Merge(m, src)
}
func (m *BattleLogMessage) XXX_Size() int {
	return xxx_messageInfo_BattleLogMessage.Size(m)
}
func (m *BattleLogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleLogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BattleLogMessage proto.InternalMessageInfo

func (m *BattleLogMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BattleLogMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *BattleLogMessage) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *BattleLogMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BattleLogFile struct {
	GameDisk             int32               `protobuf:"varint,1,opt,name=game_disk,json=gameDisk,proto3" json:"game_disk,omitempty"`
	GdxsvVersion         string              `protobuf:"bytes,2,opt,name=gdxsv_version,json=gdxsvVersion,proto3" json:"gdxsv_version,omitempty"`
	BattleCode           string              `protobuf:"bytes,3,opt,name=battle_code,json=battleCode,proto3" json:"battle_code,omitempty"`
	LogFileVersion       int32               `protobuf:"varint,4,opt,name=log_file_version,json=logFileVersion,proto3" json:"log_file_version,omitempty"`
	RuleBin              []byte              `protobuf:"bytes,10,opt,name=rule_bin,json=ruleBin,proto3" json:"rule_bin,omitempty"`
	Users                []*BattleLogUser    `protobuf:"bytes,11,rep,name=users,proto3" json:"users,omitempty"`
	BattleData           []*BattleLogMessage `protobuf:"bytes,12,rep,name=battle_data,json=battleData,proto3" json:"battle_data,omitempty"`
	StartAt              int64               `protobuf:"varint,20,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64               `protobuf:"varint,21,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BattleLogFile) Reset()         { *m = BattleLogFile{} }
func (m *BattleLogFile) String() string { return proto.CompactTextString(m) }
func (*BattleLogFile) ProtoMessage()    {}
func (*BattleLogFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bd4546689e62ffe, []int{2}
}

func (m *BattleLogFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleLogFile.Unmarshal(m, b)
}
func (m *BattleLogFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleLogFile.Marshal(b, m, deterministic)
}
func (m *BattleLogFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleLogFile.Merge(m, src)
}
func (m *BattleLogFile) XXX_Size() int {
	return xxx_messageInfo_BattleLogFile.Size(m)
}
func (m *BattleLogFile) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleLogFile.DiscardUnknown(m)
}

var xxx_messageInfo_BattleLogFile proto.InternalMessageInfo

func (m *BattleLogFile) GetGameDisk() int32 {
	if m != nil {
		return m.GameDisk
	}
	return 0
}

func (m *BattleLogFile) GetGdxsvVersion() string {
	if m != nil {
		return m.GdxsvVersion
	}
	return ""
}

func (m *BattleLogFile) GetBattleCode() string {
	if m != nil {
		return m.BattleCode
	}
	return ""
}

func (m *BattleLogFile) GetLogFileVersion() int32 {
	if m != nil {
		return m.LogFileVersion
	}
	return 0
}

func (m *BattleLogFile) GetRuleBin() []byte {
	if m != nil {
		return m.RuleBin
	}
	return nil
}

func (m *BattleLogFile) GetUsers() []*BattleLogUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BattleLogFile) GetBattleData() []*BattleLogMessage {
	if m != nil {
		return m.BattleData
	}
	return nil
}

func (m *BattleLogFile) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *BattleLogFile) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func init() {
	proto.RegisterType((*BattleLogUser)(nil), "proto.BattleLogUser")
	proto.RegisterType((*BattleLogMessage)(nil), "proto.BattleLogMessage")
	proto.RegisterType((*BattleLogFile)(nil), "proto.BattleLogFile")
}

func init() {
	proto.RegisterFile("battlelog.proto", fileDescriptor_7bd4546689e62ffe)
}

var fileDescriptor_7bd4546689e62ffe = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0x6d, 0xd3, 0x36, 0xd3, 0x14, 0x2a, 0x6b, 0x57, 0x6b, 0x04, 0x2b, 0x42, 0xb9,
	0x44, 0x1c, 0xf6, 0x00, 0x17, 0xae, 0xbb, 0xac, 0x90, 0x90, 0x00, 0x21, 0x4b, 0x70, 0x8d, 0x5c,
	0x3c, 0x44, 0xd6, 0x3a, 0x76, 0x89, 0xdd, 0x2d, 0x3c, 0x25, 0xef, 0xc0, 0x93, 0x20, 0x8f, 0x9b,
	0xf0, 0x47, 0xe2, 0x14, 0xfb, 0xfb, 0x65, 0x66, 0xbe, 0xf9, 0x64, 0xb8, 0xbf, 0x95, 0x21, 0x18,
	0x34, 0xae, 0xbd, 0xdc, 0xf5, 0x2e, 0x38, 0x96, 0xd3, 0x67, 0xf3, 0x33, 0x83, 0xd5, 0x35, 0xa1,
	0xb7, 0xae, 0xfd, 0xe8, 0xb1, 0x67, 0xe7, 0x30, 0xdf, 0x7b, 0xec, 0x1b, 0xad, 0x78, 0x56, 0x65,
	0x75, 0x21, 0x66, 0xf1, 0xfa, 0x46, 0xb1, 0x87, 0x50, 0x10, 0xb0, 0xb2, 0x43, 0x7e, 0x42, 0x68,
	0x11, 0x85, 0xf7, 0xb2, 0x43, 0x76, 0x01, 0xb0, 0xd3, 0xc6, 0x85, 0x44, 0x27, 0x44, 0x0b, 0x52,
	0x06, 0xdc, 0xca, 0x0e, 0x9b, 0x9d, 0xec, 0x65, 0xc7, 0xa7, 0x55, 0x56, 0x97, 0xa2, 0x88, 0xca,
	0x87, 0x28, 0xb0, 0x27, 0x50, 0x26, 0x7f, 0xcd, 0x67, 0xb7, 0xb7, 0x81, 0xe7, 0x55, 0x56, 0xe7,
	0x62, 0x99, 0xb4, 0x57, 0x51, 0x8a, 0xd3, 0x0f, 0xda, 0x1e, 0xf9, 0x8c, 0xf8, 0xe2, 0xa0, 0x6d,
	0x82, 0x17, 0x00, 0xc6, 0xf9, 0xa1, 0x7a, 0x4e, 0xb4, 0x88, 0x0a, 0xe1, 0x8d, 0x83, 0xf5, 0xb8,
	0xe3, 0x3b, 0xf4, 0x5e, 0xb6, 0xf8, 0xff, 0x35, 0x19, 0x4c, 0xb7, 0x4e, 0x7d, 0xa7, 0x0d, 0x4b,
	0x41, 0x67, 0xb6, 0x86, 0x89, 0xc7, 0xaf, 0xb4, 0xd6, 0x4a, 0xc4, 0x23, 0x7b, 0x04, 0x45, 0xd0,
	0x1d, 0xfa, 0x20, 0xbb, 0x1d, 0x87, 0x2a, 0xab, 0x27, 0xe2, 0xb7, 0xb0, 0xf9, 0x71, 0xf2, 0x47,
	0xaa, 0xaf, 0xb5, 0xc1, 0x68, 0x9f, 0x02, 0x50, 0xda, 0xdf, 0xd2, 0xc0, 0x5c, 0x2c, 0xa2, 0x70,
	0xa3, 0xfd, 0x2d, 0x7b, 0x0a, 0xab, 0x56, 0x7d, 0xf3, 0x77, 0xcd, 0x1d, 0xf6, 0x5e, 0x3b, 0x7b,
	0x4c, 0xb7, 0x24, 0xf1, 0x53, 0xd2, 0xd8, 0x63, 0x58, 0x8e, 0x19, 0xa9, 0x21, 0x62, 0x18, 0x22,
	0x52, 0xc8, 0x6a, 0x58, 0x1b, 0xd7, 0x36, 0x5f, 0xb4, 0xc1, 0xb1, 0xd1, 0x94, 0x26, 0xdd, 0x33,
	0xc9, 0xc5, 0xd0, 0xea, 0x01, 0x2c, 0xfa, 0xbd, 0xc1, 0x66, 0xab, 0x2d, 0x79, 0x2f, 0xc5, 0x3c,
	0xde, 0xaf, 0xb5, 0x65, 0xcf, 0x20, 0x8f, 0x39, 0x78, 0xbe, 0xac, 0x26, 0xf5, 0xf2, 0xf9, 0x69,
	0x7a, 0x2d, 0x97, 0x7f, 0x3d, 0x11, 0x91, 0x7e, 0x61, 0x2f, 0x47, 0x47, 0x4a, 0x06, 0xc9, 0x4b,
	0xaa, 0x38, 0xff, 0xb7, 0xe2, 0x18, 0xf8, 0x60, 0xf5, 0x46, 0x06, 0x19, 0x0d, 0xf8, 0x20, 0xfb,
	0xd0, 0xc8, 0xc0, 0x4f, 0x29, 0xbc, 0x39, 0xdd, 0xaf, 0x02, 0x3b, 0x83, 0x19, 0x5a, 0x15, 0xc1,
	0x19, 0x81, 0x1c, 0xad, 0xba, 0x0a, 0xdb, 0x19, 0x75, 0x7d, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x53, 0xcd, 0x9f, 0xf4, 0xc8, 0x02, 0x00, 0x00,
}
